os: Visual Studio 2015

platform:
  - x64

branches:
  only:
  - release

version: '{build}-{branch}'

cache:
  - 'node_modules'
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - cmd: echo 🚦 Authorizing Build
  - ps: if ($env:OS -eq "Windows_NT" -And $env:DEPLOY_WINDOWS -eq "0") { $host.SetShouldExit(0) }
  - cmd: git config --global core.autocrlf input

install:
  - cmd: echo 🔧 Setting up Environment
  - ps: Install-Product node 7.8.0
  - cmd: npm --global update npm

before_build:
  - cmd: echo 📥 Installing Dependencies
  - cmd: npm install

build_script:
  - cmd: echo 📦 Building
  - cmd: npm run build --metadata

deploy_script:
  - cmd: echo 📮 Deploying
  - cmd: npm run deploy

artifacts:
  - path: build\output\*.exe
  - path: build\output\*.yml

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/f29f98b58ec67b5f0f59
    method: GET
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

test: off
