matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang

language: c

branches:
  only:
    - release

cache:
  directories:
    - "$HOME/.electron"
    - "./node_modules"

addons:
  apt:
    packages:
      - bsdtar
      - g++-multilib
      - gcc-multilib
      - graphicsmagick
      - icnsutils
      - rpm
      - xz-utils

before_install:
  - echo "🚦 Authorizing Build"
  - if [[ "${OSTYPE}" == "darwin"* ]] && [[ "${DEPLOY_MACOS}" == 0 ]]; then travis_terminate 0; fi
  - if [[ "${OSTYPE}" == "linux"* ]] && [[ "${DEPLOY_LINUX}" == 0 ]]; then travis_terminate 0; fi
  - echo "🔧 Setting up Environment"
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | NVM_DIR="${HOME}"/.nvm sh
  - source "${HOME}"/.nvm/nvm.sh && nvm install 7.8.0 && nvm use 7.8.0
  - npm --global update npm

install:
  - echo "📥 Installing Dependencies"
  - npm install

script:
  - echo "📦 Building"
  - npm run build --metadata

after_success:
  - echo "📮 Deploying"
  - npm run deploy

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/24d905038aa07dda37df
    on_success: change
    on_failure: always
    on_start: never

